version: '3'
services:

  # postgres:
  #   image: postgres
  #   ports:
  #   - 5432:5432
  #   environment:
  #   - POSTGRES_PASSWORD=password

  cassandra:
    image: cassandra
    ports:
    - 7000:7000
    - 7001:7001
    - 7199:7199
    - 9042:9042
    - 9160:9160

  kafka:
    image: spotify/kafka
    ports:
    - 2181:2181
    - 9092:9092
    environment:
    - ADVERTISED_HOST=localhost
    - ADVERTISED_PORT=9092

  track_api_1:
    build: src
    command: python3 track_api_1.py
    ports:
    - 4010:4010
    - 4011:4011
    environment:
    - ZOOKEEPER_HOST=localhost
    - ZOOKEEPER_PORT=2181

  track_consumer_1:
    build: src
    command: python3 track_consumer_1.py
    ports:
    - 4020:4020
    environment:
    - KAFKA_HOST=localhost
    - KAFKA_PORT=9092
    - CASSANDRA_HOST=localhost
    - CASSANDRA_PORT=9042
